name: Vijai Kumar S
title: Vijai Kumar | Portfolio
description: Explore my portfolio and discover projects showcasing my skills in data analysis, machine learning, and data visualization. I've worked on diverse projects. This portfolio showcases my experience in transforming raw data into meaningful insights using tools like Python, SAS, and Power BI. I'm passionate about solving real-world problems and finding innovative solutions through data-driven approaches.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: vijaisvk22@gmail.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
github_username: VijaikumarSVK
linkedin_username: vijai-kumar-s
